import type { Metadata } from "next";
import styles from "./styles/Layout.module.css";
import Link from "next/link";

import mobilePhoneIcon from "/public/icons/prod-cat-mobile.svg";
import pcIcon from "/public/icons/prod-cat-pc.svg";

import wearablesIcon from "/public/icons/prod-cat-wearables.svg";
import audioIcon from "/public/icons/prod-cat-audio.svg";
import cameraIcon from "/public/icons/prod-cat-camera.svg";
import gameIcon from "/public/icons/prod-cat-game.svg";
import networkingIcon from "/public/icons/prod-cat-networking.svg";
import accessoriesIcon from "/public/icons/prod-cat-access.svg";
import Image from "next/image";
import Footer from "./components/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const categories = [
  { name: "Mobile", icon: mobilePhoneIcon, href: "/category/mobile" },
  { name: "Laptop", icon: pcIcon, href: "/category/laptop" },
  { name: "Accessories", icon: accessoriesIcon, href: "/category/accessories" },
  { name: "Tablet", icon: mobilePhoneIcon, href: "/category/tablet" },
  { name: "Camera", icon: cameraIcon, href: "/category/camera" },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className={styles.layout}>
        <nav className={styles.categoryNav}>
          {categories.map((category) => (
            <Link
              key={category.name}
              href={category.href}
              className={styles.categoryLink}
            >
              <span>
                <Image
                  alt=""
                  src={category.icon}
                  className={styles.categoryIcon}
                />
              </span>
              <span className={styles.categoryName}>{category.name}</span>
            </Link>
          ))}
        </nav>
        <main>{children}</main>
      </div>
      <Footer />
    </>
  );
}
